services:
  app:
    build:
      dockerfile: local.Dockerfile
    container_name: go-recipe-container
    restart: always
    volumes:
      - .:/app
    ports:
      - "1235:1235"
    networks:
      - allapps
      - pg
      - redis

networks:
  pg:
    name: pg
    external: true
  redis:
    name: redis
    external: true
  allapps:
    name: allapps
    external: true
